---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - web.dyatlov.net
  resources:
  - statiks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - web.dyatlov.net
  resources:
  - statiks/finalizers
  verbs:
  - update
- apiGroups:
  - web.dyatlov.net
  resources:
  - statiks/status
  verbs:
  - get
  - patch
  - update
